### ISSUE TITLE
Card stays in "Loading twitch streams..."

### ISSUE THREAD

**Issue by rzantengmail** [stefmde/HomeAssistant-TwitchFollowedLiveStreamsCard#4]
The card does not load anything. Stays in "Loading twitch streams..."

**Comment by haagar** [comment]
I see this error as well. Chrome dev tools show a 401 unauthorized error, but I haven't tracked it any farther.

**Comment by Rewur** [comment]
Same issue here

**Comment by stefmde** [comment]
The problem is that the auth process to twitch isn't that easy and HA started to support Twitch on it's own, so I rewrote the plugin to use the HA integration as data source. But that integration from HA doesn't work well on my side. It seems like its updated like every 24h or something like that. So I waited with the publication of the new version in the hope that HA will fix that issue. But in the meantime my plugin gets integrated in HACS. So I could push the new version in knowing that it also won't work or maybe work for some users or keep waiting. I also haven't much time in the last weeks so i waited. But it doesn't looks like HA is fixing that or maybe it's just on my side. So I can publish the change.

**Comment by stefmde** [comment]
That's the code I'm currently using but that doesn't work that well for me. You could that that if you want to. It should be displayed in HACS as Update: [v2.0.0](https://github.com/stefmde/HomeAssistant-TwitchFollowedLiveStreamsCard/releases/tag/2.0.0) A feedback from you would be nice.

**Comment by stefmde** [comment]
Maybe related to that: https://github.com/home-assistant/core/issues/101488

**Comment by ebbx96** [comment]
> That's the code I'm currently using but that doesn't work that well for me. You could that that if you want to. It should be displayed in HACS as Update: [v2.0.0](https://github.com/stefmde/HomeAssistant-TwitchFollowedLiveStreamsCard/releases/tag/2.0.0) A feedback from you would be nice.

Previously, I was facing the same perpetual loading issue as well for V1.0. After the update to V2.0, it now displays "Custom element doesn't exist: twitch-followed-live-streams-card." 

Are there any changes that would have to be done to the config on the user end to work with the new version?

**Comment by stefmde** [comment]
Oh sorry I made a mistake while copying the new version. I fixed it and tested it via HACS Download with the [v2.1.0](https://github.com/stefmde/HomeAssistant-TwitchFollowedLiveStreamsCard/releases/tag/v2.1.0)
Thanks for the info.
And there aren't bug changes in the config. You just don't have to provide access credentials anymore.

**Comment by ebbx96** [comment]
V2.1.0 works as expected for me. Thank you for the quick turnaround
